### ISSUE TITLE
measure_type does not match value

### ISSUE THREAD

**Issue by agustingp** [Swirrl/graphql-qb#109]
Issue running CubiQL locally
SPARQL endpoint: https://staging-drafter-sg.publishmydata.com/v1/sparql/live'
Given the following query: 
``
{ 
 dataset_recorded_crimes_and_offences{
	observations{
		total_matches
		page(first: 1000){
			count
			next_page
			observations{
				reference_area {label}
				reference_period {label}
				measure_type
				crime_or_offence
				count
				ratio
			}
		}
	}
}
}
``
Results: 
![image](https://user-images.githubusercontent.com/26118130/43530294-2162e0b2-95a5-11e8-8149-dcbbeb2f613f.png)
We can see that measure_type do not match with the value provided by the observation. Example: line 29 and line 32. We do not know if this is an issue of the dataset or if it is an issue of the API version. 
When trying the same query (below) over the online CubeQl version we are getting the following results: 
http://graphql-qb.publishmydata.com/index.html?query=%7B%20dataset_recorded_crimes_and_offences%20%7B%20observations%20%7Btotal_matches%20page%20(first%3A%202000)%7Bcount%20next_page%20observations%20%7Breference_area%20%20%7B%20label%20%7D%20reference_period%20%20%7B%20label%20%7D%20measure_type%20crime_or_offence%20ratio%20count%20%7D%7D%7D%7D%7D

Results:
![image](https://user-images.githubusercontent.com/26118130/43530306-2a21ba3e-95a5-11e8-9685-11cf6db3bd79.png)
We can see that measure_type always match the value provided by the observation. However, it is not possible to retrieve all the measures for the first X dimensions since we need to query for all the query matches for getting so.  Example: in the last query the number of matches is 63918. If we query for the first 1000 observations we will only receive as a result those for the measure COUNT, even if we reformulate the query (removing “count”) as follows  : 
{ dataset_recorded_crimes_and_offences { observations {total_matches page (first: 1000){count next_page observations {reference_area  { label } reference_period  { label } measure_type crime_or_offence ratio }}}}}
We will get a result of this style:
![image](https://user-images.githubusercontent.com/26118130/43530336-3742ba10-95a5-11e8-88a1-45c9c880f5a3.png)

In order to get the observations for the measure “ratio” we would have to query all the 63918 matches and we will be able to find these measures in the last part of the query result.

**Comment by zeginis** [comment]
@lkitching it seems that the `:mp` is bound only once for all the observations

e.g. running the following query returns all the values as ratio 
```
{ dataset_recorded_crimes_and_offences{ 
observations{ page(first: 100){
  observations{
    reference_area {label}
    reference_period{label}
    measure_type  
    count
    ratio } } }}} 
```

Currenlty we have the following code at queries.clj
```
(defn get-observation-filter-model [dim-filter]
   (let [m (-> qm/empty-model
                    (qm/add-binding [[:mp (URI. "http://purl.org/linked-data/cube#measureType")]] ::qm/var)
                    (qm/add-binding [[:mv (qm/->QueryVar "mp")]] ::qm/var))]
       (reduce (fn [m [dim value]]
                       (types/apply-filter dim m value))
                     m
                     dim-filter)))
```

Should we move somewhere lower?

**Comment by zeginis** [comment]
@lkitching any idea on this?

**Comment by lkitching** [comment]
@agustingp @zeginis - This should now be fixed on the `master` branch.
