### ISSUE TITLE
Observation ordering

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#11]
Should include both ascending and descending `direction`.

- get observations...
  - [x] ordered by the title of the area
  - [x] ordered by the value of the measure
  - [x] ordered by the value of another non-locked dimension

Below is a candidate example query demonstrating the full sort options.  The `order` parameter specifies an array of dimensions to order by, here we first order by `GENDER` and then within each gender group `REFERENCE_AREA`.  An optional map of `order_options` can be provided which lets you configure the direction of each ordering, for example here we order `GENDER` in ascending order and `REFERENCE_AREA` in descending order.  The full set of sort options should be `ASC`, `DESC`, and `CODELIST_ASC` `CODELIST_DESC`.  The later two will mean that we should use a sort order determined by the `ui:sortPriority` on Concepts in the dim/vals codelist.  We may want to consider better names for CODELIST_ASC/DESC.

```graphql
{ 
  dataset_earnings {
    uri
    title
    description
    observations(dimensions:{gender:ALL reference_period:"2009"} 
                                                order:[GENDER REFERENCE_AREA] 
                                                order_options: {GENDER: ASC REFERENCE_AREA: DESC}) {
      sparql
      total_matches
      page(first:5) {
        result {
          uri
          measure_type
          median
          reference_area
          reference_period
        }
      }
    }
  }
}
```

**Comment by zeginis** [comment]
Should we also support ordering using two or more dimensions? Eg order by year and by area.

Some times lexicographical ordering is not always appropriate e.g. for the days of the week, So other custom types of ordering should be applied.

**Comment by RickMoynihan** [comment]
> Should we also support ordering using two or more dimensions? Eg order by year and by area.

Ideally yes, though we should perhaps leave this for v2 :-)

Agree also about using something like `ui:sortPriority` on codelists, but again probably best left for v2.

**Comment by zeginis** [comment]
Ordering based on the measure value is not working properly e.g.

```
{dataset_average_household_size{
  observations(dimensions:{reference_period:{starts_after:  "2010-01-01T00:00:00Z"}}
  order:[RATIO] order_spec:{ratio:ASC}){
    page(first:1000){
      observations{
        ratio
        reference_area {
          label
          uri
        }
        reference_period {
          end
          label
          start
          uri
        } 
      }
    }
  }
}}
```

**Comment by zeginis** [comment]
I have fixed this. I'll  create a pull request including also other fixed issues.

**Comment by RickMoynihan** [comment]
Hi @zeginis I've just created a separate issue for this: https://github.com/Swirrl/graphql-qb/issues/90

Can you create PRs for each individual issue, rather than a large monolithic PR, and corresponding issues for them in the issue tracker?

It makes it significantly easier to review changes, and incoroporate fixes.

**Comment by zeginis** [comment]
This issue has been fixed. Now #90 is pending
