### ISSUE TITLE
Replace ASK queries

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#134]
Due to known [bug at Virtuoso triple store](https://github.com/openlink/virtuoso-opensource/issues/464) ASK SPARQL queries do not work properly. As a result CubiQL cannot run on top of many versions of Virtuoso (including the latest one) that is used by most OGI partners.

CubiQL has only one ASK query that can be replaced by an equivalent SELECT query.

ASK query:
```
ASK WHERE {
  ?obs a qb:Observation .
  ?obs ?measure ?val .
  FILTER(isNumeric(?val))
}
```

Equivalent SELECT:
```
SELECT ?obs WHERE {
  ?obs a qb:Observation .
  ?obs ?measure ?val .
  FILTER(isNumeric(?val))
}LIMIT 1
```

@lkitching is this feasible?

**Comment by lkitching** [comment]
@zeginis - I've created https://github.com/Swirrl/graphql-qb/pull/136 for this issue if you could take a look? Thanks.

**Comment by lkitching** [comment]
Fixed by https://github.com/Swirrl/graphql-qb/pull/136
