### ISSUE TITLE
Get error message

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/graphql-qb#139]
Using http://graphql-qb.publishmydata.com/graphql with query

```
{cubiql{
  datasets {
    uri
    title
    description
  } 
}}
```
works

Having a local graphql running on port 8888 with in the backend a fuseki with sparql endpoint http://localhost:3030/zendmasten/query
I get for the same query
`{
  "errors": [
    {
      "message": "Cannot query field `cubiql' on type `QueryRoot'.",
      "query-path": [],
      "locations": [
        {
          "line": 3,
          "column": 0
        }
      ],
      "field": "cubiql",
      "type": "QueryRoot"
    }
  ]
}`
What am I missing?

**Comment by PaulZH** [comment]
@zeginis using the latest github release 0.2.0
@lkitching  now getting while using another dataset
`Exception in thread "main" clojure.lang.ExceptionInfo: Argument `order' of field `dataset_dataset_1/observations' references unknown type `dataset_dataset_1_dimension_measures'. {:field-name :dataset_dataset_1/observations, :arg-name :order, :schema-types {:scalar [:Boolean :DateTime :Float :ID :Int :SparqlCursor :String :uri], :object [:MutationRoot :QueryRoot :SubscriptionRoot :dataset :dataset_dataset_1 :dataset_dataset_1_observations :dataset_dataset_1_observations_aggregations :dataset_dataset_1_observations_page :dataset_dataset_1_observations_page_observations :dim :enum_dim_value :measure :ref_area :ref_period :unmapped_dim_value], :union [:dim_value], :interface [:dataset_meta :resource], :input-object [:dataset_dataset_1_observations_dimensions :dataset_dataset_1_observations_order_spec :filter :page_selector :ref_period_filter], :enum [:sort_direction]}}
`

**Comment by lkitching** [comment]
@PaulZH - Version `0.2.0` is quite old, I've created a new release `0.3.0` containing the latest version available [here](https://github.com/Swirrl/graphql-qb/releases/tag/0.3.0). Please let me know if you have any problems with it.

**Comment by PaulZH** [comment]
Thanks, up and running now.
