### ISSUE TITLE
Issue with skos:member

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/graphql-qb#140]
`{cubiql{
  dataset_xxxx {
    title
    description
    dimensions {
      uri
      values {
        ... on resource {
          label
          uri
        }
        ... on enum_dim_value {
          enum_name
        }
      }
    }
  }
}}
`
values are not populated in our case, since this translates into following query
'
PREFIX qb: <http://purl.org/linked-data/cube#>PREFIX skos: <http://www.w3.org/2004/02/skos/core#>PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>PREFIX ui: <http://www.w3.org/ns/ui#>SELECT ?dim ?member ?label WHERE {<http://proxml.com/id/dataset/weather> qb:structure ?struct .?struct a qb:DataStructureDefinition .?struct qb:component ?comp .?comp qb:dimension ?dim .?comp <http://purl.org/linked-data/cube#codeList> ?list .?list skos:member ?member .OPTIONAL {  ?member <http://www.w3.org/2000/01/rdf-schema#label> ?label .}}
'
which is using skos:member being only correct for skos:Collections. 
While in the spec  
' Property: qb:codeList ( Domain: qb:CodedProperty -> Range: owl:unionOf(skos:ConceptScheme skos:Collection qb:HierarchicalCodeList) )'
We are using skos:ConceptSchemes.
The existing code doesn't work for qb:HierarchicalCodeLists either.

See the corresponding error in table2qb: using skos:member with skos:ConceptScheme and hence having semantically an inconsistent dataset.

**Comment by lkitching** [comment]
Fixed by 1263de3b42761ec77925e7fa2e163bd10bdb9b2a
