### ISSUE TITLE
Document end-to-end example using table2qb

### ISSUE THREAD

**Issue by lkitching** [Swirrl/graphql-qb#142]
Add documention for an end-to-end example that uses both [table2qb](https://github.com/Swirrl/table2qb/) and CubiQL:

* Take the csv files
* Create the ttl using Table2QB
* Run CubiQL on these data

**Comment by zeginis** [comment]
@lkitching  I have some problems running Table2QB: https://github.com/Swirrl/table2qb/issues/77

Any idea what is the problem?

**Comment by zeginis** [comment]
Fixed by 0474edf6adc585761776430c7610c1da99001168
