### ISSUE TITLE
Listing measures for a cube

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#19]
This query currently doesn't work

http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20datasets%20%7B%0A%20%20%20measures%20%7B%0A%20%20%20%20uri%0A%20%20%7D%20%0A%20%7D%0A%20%20%0A%7D%0A

**Comment by lkitching** [comment]
Fixed in 1292a8baf7709f4de012a8756b731ed6afb5892d
