### ISSUE TITLE
Allow configuration of arbitrary SPARQL endpoints

### ISSUE THREAD

**Issue by lkitching** [Swirrl/graphql-qb#24]
Allow the SPARQL endpoint to search for datasets to be configuration rather than using the test repository loaded from resources.

**Comment by zeginis** [comment]
I agree.
I am currently expanding the "search cube" functionality. But I cannot adequately test it with the test repository that contains only 2 cubes.

**Comment by RickMoynihan** [comment]
Even without supporting extra repositories it should be relatively straightforward to add extra rdf data to the resources directory and add it to the [list of files loaded](https://github.com/Swirrl/graphql-qb/blob/master/src/graphql_qb/data.clj#L12) in the resource-repo.

Before you get too far though @zeginis I'd suggest you write up your plans for what you want the queries / schema to look like on issue #21 to support all of the use cases we want.

**Comment by lkitching** [comment]
Fixed in 2603e550ea47618873369f0376ed3d3dd98598cb
