### ISSUE TITLE
Make the dimension value enum values more easily discoverable

### ISSUE THREAD

**Issue by BillSwirrl** [Swirrl/graphql-qb#25]
To filter data by specifying the value of a dimension, you need to provide the appropriate ENUM value for the desired member of the dimension codelist.

It would be useful if these were returned as part of the results of the dimension value list, so that a user can easily see/select what value to choose in a subsequent filtering query

**Comment by lkitching** [comment]
Fixed in 1292a8baf7709f4de012a8756b731ed6afb5892d

**Comment by RicSwirrl** [comment]
@lkitching can you add an example to the readme please?

**Comment by RicSwirrl** [comment]
@lkitching I tried this:

```
dimensions {
      uri
      values {
        label
        uri
        enum_name
      }
    }
```

...but it doesn't return any enum values for refperiod and refarea? How do I lock to a single period?  Ideally we shouldn't special-case any dimensions.
