### ISSUE TITLE
Fix observations query to work for datasets with multiple measures

### ISSUE THREAD

**Issue by lkitching** [Swirrl/graphql-qb#27]
Datasets with multiple measures (e.g. http://statistics.gov.scot/data/economic-inactivity) generate one observation per measure rather than associating multiple measure  values with a single observation. The SPARQL query generated to match multiple observations constrains all measures simultaneously so will fail to match any observations since none have multiple measure values.

**Comment by RicSwirrl** [comment]
see also #34

**Comment by zeginis** [comment]
This issue has been solved. However the current solution uses `OPTIONAL `clauses that cause timeout exceptions. See #87
