### ISSUE TITLE
Aggregating Observations

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#3]
We may want to consider what aggregations might look like.  Are they even needed?

- Aggregations: Given a set of criteria for finding observations (above)...
  - [x] get the count of observations which match the criteria
  - [x] get the average of the measure values
  - [x] get the sum of the measure values
  - [x] min
  - [x] max
  - [ ] custom aggregations (e.g. Standard deviation of the measure values)

**Comment by zeginis** [comment]
You mean to use aggregations for the requested cube slices? 

At the previous version of the API (https://github.com/OpenGovIntelligence/json-qb-api-implementation) we supported the computation of aggregations accross dimensions. All possible dimension combinations are used to create aggregations.

For example if a cube has three dimensions (e.g. time, geographical location, sex) the Data Cube Aggregator will compute aggregations and create new cubes with one and two dimensions based on the original cube’s observations.

The supported aggregation function:  AVG, SUM, MIN, MAX, COUNT

**Comment by RickMoynihan** [comment]
Closing as done, and created a new issue for custom aggregations.
