### ISSUE TITLE
Search by measured value

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#32]
For example find dataset that have unemployment over 20%

Expected GraphQL queries:

```
{ datasets(data: {
             and/or: [ { measure:"http://statistics.gov.scot/def/measure-properties/count”    
                        value:”1000”}
                      { measure:"http://statistics.gov.scot/def/measure-properties/count”    
                        value:”2000”}]}) {
       title
}}
```

```
{ datasets(data: {
        greater/smaller: [ { measure:"http://statistics.gov.scot/def/measure-properties/count”    
                           value:”1000”}]}) {
       title
}}
```

Required changes at schema: the same as #30

**Comment by BillSwirrl** [comment]
I suspect that selecting observations within a specific dataset based on the value is likely to be a more common use case than selecting datasets according to whether any observation has a particular value?  Dimitris - do you have a particular use case in mind for this?

**Comment by zeginis** [comment]
To be honest I do not have a particular use case in mind!

We discuss it also with Evangelos and I think we can leave this functionality, at least for the moment.

**Comment by zeginis** [comment]
We will not support this functionality
