### ISSUE TITLE
find dataset by URI returns duplicate results (sometimes)

### ISSUE THREAD

**Issue by RicSwirrl** [Swirrl/graphql-qb#36]
e.g. try:

```
{
  datasets(uri:"http://statistics.gov.scot/data/corporate-insolvency") {
    description
    schema
    title
    uri
  }
}
```

You get 2 results

**Comment by BillSwirrl** [comment]
That dataset is declared as a qb:DataSet in both data and metadata graphs (one of those historic glitches before the pipelines were sorted maybe?). Haven't looked at the query that is executed yet, but it is probably something to do with that

**Comment by zeginis** [comment]
I think @BillSwirrl is right.

I run the following query and it returns duplicates at different graphs (data and metadata)
```
PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT ?ds ?g WHERE {
  GRAPH ?g{
   ?ds a qb:DataSet .
}}
```

At the pull request #38 I use DISTINCT to avoid duplicates

**Comment by zeginis** [comment]
This has been fixed:

I run the CubiQL query and there are no duplicates:
```
{
  datasets(uri:"http://statistics.gov.scot/data/corporate-insolvency") {
    description
    schema
    title
    uri
  }
}
```
