### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#46]
I try to create a simple javascript application that uses CubiQL.
I use simple $.ajax GET gueries and get 
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by RickMoynihan** [comment]
Thanks for reporting this @zeginis.

It looks like we need to setup [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).  I would've thought [lacinia-pedestal](https://github.com/walmartlabs/lacinia-pedestal) would've enabled it by default, but apparently not.

**Comment by islab-uom** [comment]
Hi @RickMoynihan,

Any progress on this issue? Are there any alternative solutions?

**Comment by zeginis** [comment]
Any updates on this? 
How can I do this at the CubiQL  instace running at our server?

**Comment by lkitching** [comment]
@zeginis  - I have updated the nginx config on the server to add the required CORS headers, please let me know if this is now working for you.

**Comment by zeginis** [comment]
@lkitching - I have tried but the problem still remains.

I get get the following error:

`Failed to load http://graphql-qb.publishmydata.com/graphql: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8082' is therefore not allowed access. The response had HTTP status code 400.`

**Comment by lkitching** [comment]
@zeginis  - Can you add the request(s) your sending and the responses you receive? The `Access-Control-Allow-Origin` header should always be set to `*` in the response.

**Comment by lkitching** [comment]
@zeginis - CORS is now enabled in the application itself so you can also try running the service locally from the latest version of `master` and cross-origin requests should be permitted.

**Comment by RickMoynihan** [comment]
@zeginis confirmed on the call that this is now resolved for them.
