### ISSUE TITLE
Upgrade lacinia and lacinia-pedestal

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#49]
We currently use:

`[com.walmartlabs/lacinia "0.20.0"]`
`[com.walmartlabs/lacinia-pedestal "0.3.0"]`

We should upgrade to the latest versions of both.  

- `0.4.0` of `lacinia-pedestal` may also help with #47 because you can now [use a function instead of schema](https://github.com/walmartlabs/lacinia-pedestal/blob/master/CHANGELOG.md#040----24-oct-2017).

**Comment by lkitching** [comment]
Fixed in c78639d
