### ISSUE TITLE
JSON LD support?

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#5]
It would be worth investigating how we could incorporate JSON-LD context blocks with the graphql approach.

The advantage would be that the context blocks would give us a more principled way to map between URIs and CURIs.  

It seems we could either:

- Include a context block in a [HTTP Link header](https://json-ld.org/spec/latest/json-ld/#interpreting-json-as-json-ld).  This could either be global, or customised per response.
- Include a context block schema as a child of the graphql QueryRoot.  This would allow it to be returned in the data.

**Comment by zeginis** [comment]
One of the limitations of GraphQL is the luck of support for namespaces, so all schemas exist in a single global namespace.  There are no native features for prefixing or aliasing names to shorter ones. 

Can JSON-LD help to fix this problem?

**Comment by RickMoynihan** [comment]
We've decided to abandon this approach as JSONLD is almost incompatible with graphql responses.

You could do stuff with a context map in a `Link` header but it'd be a lot of work for little benefit for the majority of our target users.
