### ISSUE TITLE
CubiQL stop responding after some requests

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#77]
I run CubiQL on top of our SPARQL endpoint: http://195.251.218.39:8891/sparql

After some calls it stops responding. E.g. I run the following query 4-5 times and then it stops responding. Then I have to restart CubiQL. It does  not produce any exception. Any idea why this happens?

```
{dataset_vehicles_fueltype{observations{
  page{
    result{
      count_of_vehicles
      fuel_type
      measure_type
}}}}}
```

**Comment by RickMoynihan** [comment]
Ok I've seen this before in other code.  It looks like there's probably some issues cleaning up connections, leading to deadlock on the connection pool.

e.g. this pattern for querying should be deprecated: https://github.com/Swirrl/graphql-qb/blob/master/src/graphql_qb/resolvers.clj#L62

@lkitching As a quick work around I'd recommend replacing all callsites that use `repo/query` with a definition of an `eager-query` in your project.

Something like this should solve it:

```clojure
(defn eager-query [repo query-str]
  (with-open [conn (repo/->connection repo)]
     (doall (repo/query query-str))))
```

I plan to deprecate the grafter `repo/query` function with explicitly eager/lazy variants.  I also want to make queries transducible/eager at some point too.

**Comment by lkitching** [comment]
@zeginis - I've pushed 67981d96f0c62af32472ac687622b2fe301e56c9 which implements @RickMoynihan 's suggestions, could you try this version against your endpoint? There were a couple of queries which could cause the problem you're seeing. I couldn't reproduce locally due to a schema error on startup when run against your data.

**Comment by RickMoynihan** [comment]
Thanks @lkitching, regardless of whether it fixes @zeginis issue this is a good fix to have.

**Comment by zeginis** [comment]
Thank you @lkitching this fixed the issue!

**Comment by RickMoynihan** [comment]
Great.

Thanks both.
