### ISSUE TITLE
Get dimension value URI's / Label's for all dimensions

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/graphql-qb#79]
This was split out as an interim step from the larger issue #55.

**Comment by RickMoynihan** [comment]
Done in 903775f93d13f614cf734100092090f394b18970

Allows queries [such as this](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20%20dataset_poverty%20%7B%0A%20%20%20%20dimensions%20%7B%0A%20%20%20%20%20%20uri%0A%20%20%20%20%20%20values%20%7B%0A%20%20%20%20%20%20%20%20...%20on%20unmapped_dim_value%20%7B%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20enum_dim_value%20%7B%0A%20%20%20%20%20%20%20%20%20%20enum_name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) to get dimension values out.

This commit creates some common interfaces, allowing `... on XXXXX` style queries.

The types are currently called:

- `unmapped_dim_value` (currently refArea's/refPeriod's but for dim-value types that we don't map into explicit schema types)
- `enum_dim_value` (types with an `enum_name` that we also do schema gen for elsewhere)

There is also an interface called `resource` that is for anything with `uri` and `label`, both of the above concrete types implement this.  You can also [query for `resource` instances](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20%20dataset_poverty%20%7B%0A%20%20%20%20dimensions%20%7B%0A%20%20%20%20%20%20uri%0A%20%20%20%20%20%20values%20%7B%0A%20%20%20%20%20%20%20%20...%20on%20resource%20%7B%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20...%20on%20enum_dim_value%20%7B%0A%20%20%20%20%20%20%20%20%20%20enum_name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by RickMoynihan** [comment]
@zeginis This is currently done and [deployed on the test server](graphql-qb.publishmydata.com/index.html).

This is an intermediate fix that will likely evolve in the future as part of #55.  Also some things such as the types/interfaces being on the `values` rather than the `dimensions` will likely change in a breaking way.  Though I suspect the queries will break, though the data you receive back will likely stay in the same shape.

I hope this helps resolve some of your main issues at the moment.  Happy to discuss as always.

**Comment by zeginis** [comment]
@RickMoynihan I try to run the fix on our data but get some exceptions during schema creation.

Does the fix require a code list for the refArea and refPeriod?

**Comment by RickMoynihan** [comment]
Yes.  Currently we assume these lists contain the set of values used in the dataset, not the wider list of values.

Just a note that we said on the call today that we'll discuss code list management processes and recommendations next year.
