### ISSUE TITLE
Cannot construct identifier from label 'Αριθμός Οχημάτων'

### ISSUE THREAD

**Issue by mohadelrezk** [Swirrl/graphql-qb#82]
This happens when I try to run the the latest code of the service:

![screen shot 2018-04-16 at 17 58 30](https://user-images.githubusercontent.com/17986166/38824087-0e798ce8-41a0-11e8-87e5-f498157178ea.png)

**Comment by zeginis** [comment]
This is the same issue as #73. The problem is that the API currently supports only English labels. The exception is created because the label is in Greek.
