### ISSUE TITLE
Supporting 'GET slice' from the old API version

### ISSUE THREAD

**Issue by mohadelrezk** [Swirrl/graphql-qb#84]
We need this for our tools.

It was supported on the old API (https://github.com/OpenGovIntelligence/json-qb-api-implementation)

example of the required API response:

http://wapps.islab.uom.gr:8084/JSON-QB-REST-API/slice?dataset=http://id.mkm.ee/statistics/def/cube/crashes&limit=100&mode=label

**Comment by RickMoynihan** [comment]
We support currently support arbitrary slices through [queries such as this](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20dataset_earnings%20%7B%0A%20%20%20%20title%0A%20%20%20%20description%0A%20%20%20%20observations(dimensions%3A%7Bgender%3AALL%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20population_group%3AWORKPLACE_BASED%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20measure_type%3AMEDIAN%7D)%20%7B%0A%0A%20%20%20%20%0A%20%20%20%20%20%20page%20%7B%0A%20%20%20%20%20%20%20%20result%20%7B%0A%20%20%20%20%20%20%20%20%20%20gender%0A%20%20%20%20%20%20%20%20%20%20measure_type%0A%20%20%20%20%20%20%20%20%20%20population_group%0A%20%20%20%20%20%20%20%20%20%20reference_area%0A%20%20%20%20%20%20%20%20%20%20reference_period%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20start%0A%20%20%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%20%20median%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by mohadelrezk** [comment]
Can I query observations with sorting and limit options?

**Comment by RickMoynihan** [comment]
@mohadelrezk yes.

See the `order:` option on `observations` field.  And the `first:` and `after:` options on `page`, along with the accompanying page fields `next_page` `count` etc.  I've written an example [query here for you](http://graphql-qb.publishmydata.com/index.html?query=%7B%0A%20%20dataset_earnings%20%7B%0A%20%20%20%20title%0A%20%20%20%20description%0A%20%20%20%20observations(dimensions%3A%7Bgender%3AALL%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20population_group%3AWORKPLACE_BASED%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20measure_type%3AMEDIAN%7D%0A%20%20%20%20%20%20order%3A%20GENDER)%20%7B%0A%0A%20%20%20%20%0A%20%20%20%20%20%20page(first%3A%203%0A%20%20%20%20%20%20%20%20%20%20%20after%3A%20%22AAAAAAAAAAM%3D%22)%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%20%20next_page%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20result%20%7B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20gender%0A%20%20%20%20%20%20%20%20%20%20measure_type%0A%20%20%20%20%20%20%20%20%20%20population_group%0A%20%20%20%20%20%20%20%20%20%20reference_area%0A%20%20%20%20%20%20%20%20%20%20reference_period%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20end%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%20%20start%0A%20%20%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20uri%0A%20%20%20%20%20%20%20%20%20%20median%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)



For more details see the pagination links in the [README](https://github.com/Swirrl/graphql-qb#pagination)

**Comment by mohadelrezk** [comment]
ok, is there away to make that query without defining result field?
for example:
`
{
  dataset_earnings {
    observations(
      order: Date) {
      page(first: 300
           after: $page) {
        count
        next_page
        result{} 
          
        }
    }
  }
}

`

**Comment by mohadelrezk** [comment]
After the discussion we had on last meeting, I think providing an option 'ALL' to retrieve all the dim/measures values of an observation will solve our issue.

**Comment by RickMoynihan** [comment]
Hi @mohadelrezk sorry I missed your follow up questions.  Also what meeting are you referring to?  To my knowledge I don't think anyone from Swirrl was there.

Ok, I think I understand now what you're asking for; but this isn't expressible with the current graphql schema.  You could do it by querying for our dataset specific schema and building a query targetting it, but it'd not be easy.

We've initially targetted use cases that baked dataset specific knowledge into the schema; to make it easy to browse/query what is there via graphiql.  However we haven't added  generic functionality

We currently generate precise schema per dataset, but don't yet offer the ability to query at a generic level without knowing dataset specifics.

It's not entirely trivial to add an `ALL` option, instead we need to build a new bit of schema which has a more generic interface.

I've openned a new issue with a proposed example query in it.  See the new issue #85.

**Comment by RickMoynihan** [comment]
@mohadelrezk Sorry I should also have said, it would be useful if you could take a look at the proposed query in #85 and figure out if there are any missing features etc in it, and what it might look like.  

I'd also like to run it by @zeginis too before we start any work on implementing.

**Comment by mohadelrezk** [comment]
I was refereeing to the discussion I had with @zeginis during today teleco.

**Comment by zeginis** [comment]
@RickMoynihan today we had an OGI technical telco. I proposed as an example to use the `ALL` option to get all available dimensions at the result.  I'll have a better look at #85 to see if cover all the options.

@mohadelrezk I was wondering why don't you use 2 CubiQL queries to get the results to need?:
- Use one query to get all the available cube dimensions e.g.
```
{ dataset_earnings {
    dimensions {
      enum_name
      uri
}}}
```
- use another query to get the results

```
{dataset_earnings {  
  observations(dimensions:{gender:ALL  population_group:WORKPLACE_BASED measure_type:MEDIAN}  
order: GENDER) {    
      page(first: 3 after: "AAAAAAAAAAM=") {
        result {          
          gender
          measure_type
          population_group
          reference_area
          reference_period
 } } } } }
```
At my understanding one should first use some CubiQL queries to explore the structure of the cube and then use another query to get the observations. Is this not appllicable to your tools?

@RickMoynihan the enum names of the dimensions are with capital leters (e.g. GENDER) while at the `results` we use normal letters (e.g. gender) is this ok?

**Comment by mohadelrezk** [comment]
@zeginis  If this feature won't be supported I will used the method you have proposed.

**Comment by zeginis** [comment]
@mohadelrezk this functionality won't be supported at the next version of CubiQL. Go ahead with the two step method I proposed above.

**Comment by mohadelrezk** [comment]
while trying this query:
`
{
  datasets (uri:"http://statistics.gov.scot/data/earnings") {

    observations {
      total_matches
      page {
        count
        next_page
        observations {
          gender
          measure_type
          median
          population_group
          uri
          reference_area {
            label
            uri
          }
          reference_period {
            label
            uri
          }
          measure_type
        }
      }
    }
  }
}
`
I faced this error:
**Cannot query field `observations' on type `dataset'.**
but this query work fine if I use:
`{
  dataset_earnings {

    observations {
      total_matches
      page {
        count
        next_page
        observations {
          gender
          measure_type
          median
          population_group
          uri
          reference_area {
            label
            uri
          }
          reference_period {
            label
            uri
          }
          measure_type
        }
      }
    }
  }
}`

**Comment by mohadelrezk** [comment]
can I query enum name of dataset?

**Comment by zeginis** [comment]
@mohadelrezk you cannot get observations from using the `datasets(uri: XXX)` you can only get metadata e.g. dimensions, measures etc. In order to get the observations you need to use the dataset enum name

In order to get the enum name of the dataset, dimensions, measures you can use the query:

```
{datasets(uri:"http://statistics.gov.scot/data/earnings"){
  schema
  uri 
  dimensions {
    enum_name
    uri
  }
  measures {
    enum_name
    label
    uri
  } 
}}
```

**Comment by mohadelrezk** [comment]
@zeginis I found that I also need to define the attributes of a dimension or measure to get its observation

**for example this doesn't work:**

```
{dataset_earnings{
observations {
total_matches
page (first: "500"){
count
next_page
observations {
reference_area
reference_period
gender
measure_type
population_group
median
 }}}}}
```
**but this do work:**
```
{dataset_earnings{
observations {
total_matches
page (first: "500"){
count
next_page
observations {
reference_area{
label
uri
}
reference_period{
label
uri
}
gender
measure_type
population_group
median
 }}}}}
```
regarding that the dim/measures enums are returned in upper case letters and should be queries in lower case letter [I think this already a reported issue, right? ]

**Comment by zeginis** [comment]
@mohadelrezk  for dimensions that have 2nd level properties like reference area and reference period you need to define their attributes. 

The enums problem is not reported  as a separate issue.
