### ISSUE TITLE
Running CubiQL on default data

### ISSUE THREAD

**Issue by arekstasiewicz** [Swirrl/graphql-qb#98]
According to the documentation: 
> If the endpoint is not specified the built-in test data will be used.

Running:
`java -jar graphql-qb-0.2.1-SNAPSHOT-standalone.jar`

produces the following error:
> Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :to-statements of protocol: #'grafter.rdf.protocols/ITripleReadable found for class: nil

![screen shot 2018-07-02 at 18 03 53](https://user-images.githubusercontent.com/2188771/42230090-09693730-7ee0-11e8-8da1-cea2f18efc67.png)

**Comment by lkitching** [comment]
@arekstasiewicz - Apologies, we used to include the test data in the uberjar but this has now moved into the `data` directory within the repository. If you're in the repository root directory you can use the test data with:

    java -jar target/uberjar/graphql-qb-0.2.1-SNAPSHOT-standalone.jar --endpoint data

**Comment by arekstasiewicz** [comment]
perfect, thanks!

**Comment by arekstasiewicz** [comment]
Sorry to re-open it, but it seems that version 0.4 is not able to load default data and shows error 'Endpoint required'.

Uploading the sample data to Virtuoso produces the following:

![screen shot 2018-09-13 at 11 50 52](https://user-images.githubusercontent.com/2188771/45484203-4ef66180-b74b-11e8-8a3a-a19aa0e47a26.png)

(no error in the command-line / log)

**Comment by zeginis** [comment]
Does the error appear only at the `datasets` query? 
Can you query an individual dataset e.g. for title ?
e.g.
```
{cubiql{
  dataset_births {
  title  }}}
```

**Comment by arekstasiewicz** [comment]
Unfortunately no.

![screen shot 2018-09-13 at 13 11 34](https://user-images.githubusercontent.com/2188771/45487571-a51cd200-b756-11e8-8926-a540f74f0902.png)

**Comment by arekstasiewicz** [comment]
Same results - server returns error 500. There are 2 datasets available.

![screen shot 2018-09-13 at 13 35 28](https://user-images.githubusercontent.com/2188771/45488656-fb3f4480-b759-11e8-99c4-edbdac0e9226.png)

**Comment by zeginis** [comment]
Can you paste the exception from the log?

**Comment by arekstasiewicz** [comment]
It is empty: command line and cubiql.log
Is it possible to config log level?

**Comment by zeginis** [comment]
Is the SPARQL endpoint public to test?

**Comment by arekstasiewicz** [comment]
I am running it locally using latest master version. Tested on 2 different machines: Ubuntu + OS X.

**Comment by lkitching** [comment]
@arekstasiewicz - I've pushed a fix for the default data to `master`, can you see if it works for you? Does the error with the virtuoso endpoint persist?

**Comment by arekstasiewicz** [comment]
@lkitching thanks, I was able to run:
`java -jar graphql-qb-0.4.0-SNAPSHOT-standalone.jar --endpoint data`

Using Virtuoso produces same error.
