### ISSUE TITLE
Configure CubiQL to run with other data

### ISSUE THREAD

**Issue by zeginis** [Swirrl/graphql-qb#99]
We should allow the user to configure CubiQL to make it run with other data:
- Define the geo dimension. Currently it is hardcoded --> http://purl.org/linked-data/sdmx/2009/dimension#refArea
- Define the time dimension. Currently it is hardcoded --> http://purl.org/linked-data/sdmx/2009/dimension#refPeriod
- Define the concept associated with a code list. Currently CubiQL searches at qb:ComponentSpecification, however QB Vocabulary requires the code list to be defined at the qb:DimensionProperty (#68) .
- Define the label properties. Currently only rdfs:label is used. There could be more than one e.g. rdfs:label, skos:prefLabel. (It is usual skos:Concepts to use skos:prefLabel)(#69)

Some of the existing data restrictions for CubiQL (described at PR #92) could be bypassed with such a configuration.

**Comment by zeginis** [comment]
@RickMoynihan @lkitching are you using any specific library for the configuration of clojure apps?

**Comment by zeginis** [comment]
@RickMoynihan @lkitching I have identified some libraries for this:
- https://github.com/juxt/aero
- https://github.com/yogthos/config
- https://github.com/metosin/maailma

Are you using any of them at your clojure apps?

**Comment by zeginis** [comment]
I will go on with aero -> https://github.com/juxt/aero
It covers our needs and is quite simple

**Comment by RickMoynihan** [comment]
Yes, we use aero a lot, I'd suggest you give that a try. 👍
